output = tCl, gwCl, OmGW

f_pivot = 3e-3 ; For LISA. We should check if this value will change our results.
f_min = 1e-5
f_max = 1

l_max_scalars = 15

f_dec_ini = 0

gwb_source_type = PBH_gwb
A_star = 0.0046
f_star = 0.013
f_NL = 0


gravitational_wave_contributions = ad, tsw, pisw, eisw, lisw, ini

modes = s

ic = ad

write_warnings = yes
primordial_verbose = 1
convert_gwb_to_energydensity = yes

; 1. 能否回到别人的结果
; 2. C_l 测试
